arm_left:
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

base_to_second_joint_position_controller:
    type: effor_controllers/JointPositionController
    joint: arm_l_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}